### ISSUE TITLE
Extra space after periods in dumped strings

### ISSUE THREAD

**Issue by Advent-Seph** [denikson/CM3D2.YATranslator#12]
When dumping strings, particularly the descriptions of items in the Maid Edit screen, if the description has a period in the middle of the sentence, the dumped string will add an extra space after the period which needs to be erased for the translation to work properly.

I checked this a few times over and it's repeatable with Maid Edit item descriptions, regardless of whether level dumping is set to "-1" or "5".

The extra space will be there, but (i'm imagining due to the nature of japanese text) isn't visible just by looking at it, but moving through the sentence with the arrow keys reveals it.

**Comment by ghorsington** [comment]
Part of the change: updated info about [string translations](https://github.com/denikson/CM3D2.YATranslator/wiki/Translatable-resources#translation-file-structure) to better inform of valid string translation structure.

Main notes:

1. YAT removes all newlines and trailing spaces from the original text before translating it.
2. Any other special characters that may exist in the original text must be escaped in the translation files.

If string dumping is enabled YAT will dump the strings with newline (\n) characters removed and other special characters escaped. In other words, dumped strings can be used as-is in the translation files.
