### ISSUE TITLE
Photo mode post edit bug

### ISSUE THREAD

**Issue by YuliaS11** [denikson/CM3D2.YATranslator#21]
[Com3d2]
Been having this problem for a long time, but can confirm now that YATranslator prevents pose edit menu from working.

**Comment by ghorsington** [comment]
Sounds like a duplicate of #20.

Please elaborate more if the issue is totally unrelated to #20.

**Comment by YuliaS11** [comment]
Cannot you put this on the common issue and solution page?

**Comment by ghorsington** [comment]
That is indeed a fine idea! I updated the [Troubleshooting page](https://github.com/denikson/CM3D2.YATranslator/wiki/Troubleshooting#common-issues-and-solutions) to remind to check GitHub issue tracker for common issues and solutions.  
After all, GitHub issue tracker is a place to check for common issues and solutions.

**Comment by YuliaS11** [comment]
Also, do you know how to stop names from being translate?

**Comment by ghorsington** [comment]
They aren't, unless you explicitly translate them.   
However, if you have AutoTranslate installed, it will translate anything it sees -- including names.
