### ISSUE TITLE
Reloading Assets' textures with F12.

### ISSUE THREAD

**Issue by krypto5863** [denikson/CM3D2.YATranslator#4]
Unified Translation Loader reloaded the Assets folder when you pressed F12. I can see that YAT does reload strings but it doesn't seems to reload the Assets folder.

For example. If replace an Asset texture with another one and hit F12, The texture isn't changed.

This is a feature I used quite frequently when I did edits to the translations and do still make use of. Any way you could implement it? Not sure if it's there already...

**Comment by ghorsington** [comment]
The feature is already implemented in YAT, but it seems it doesn't work unless `EnableStringReload` is set to true (which of course does not make sense). Fixing.
